deploy: 67efdaccf9ef9d7f93d93a3800c10bfead8a3590

diff --git a/dev/as-requestor b/dev/as-requestor
--- a/dev/as-requestor
+++ b/dev/as-requestor
@@ -3,35 +3,38 @@
 
 set -u
 
+GOLEM_ACCEPT_TOS="${GOLEM_ACCEPT_TOS:-no}"
+BATCH_MODE="${BATCH_MODE:-no}"
+
 YA_INSTALLER_VARIANT=requestor
 select_version() {
   echo "available versions:"
-  echo "0) v0.10.1 Fertile Soil"
-  echo "1) v0.10.1-rc3 #222"
-  echo "2) v0.10.1-rc2 #220"
-  echo "3) v0.10.1-rc1 #219"
-  echo "4) v0.10.0-reputation-5 #221"
+  echo "0) v0.12.0-rc3 #238"
+  echo "1) v0.12.0-rc2 #237"
+  echo "2) v0.11.0 Hidden Secret"
+  echo "3) v0.12.0-rc1 #235"
+  echo "4) v0.11.0-rc11 #234"
   while true; do
     read -r -u 2 -p "Select version: " ANS || exit 1
     case "$ANS" in
     0)
-    YA_INSTALLER_CORE="v0.10.1"
+    YA_INSTALLER_CORE="pre-rel-v0.12.0-rc3"
      return
 ;;
     1)
-    YA_INSTALLER_CORE="pre-rel-v0.10.1-rc3"
+    YA_INSTALLER_CORE="pre-rel-v0.12.0-rc2"
      return
 ;;
     2)
-    YA_INSTALLER_CORE="pre-rel-v0.10.1-rc2"
+    YA_INSTALLER_CORE="v0.11.0"
      return
 ;;
     3)
-    YA_INSTALLER_CORE="pre-rel-v0.10.1-rc1"
+    YA_INSTALLER_CORE="pre-rel-v0.12.0-rc1"
      return
 ;;
     4)
-    YA_INSTALLER_CORE="pre-rel-v0.10.0-reputation-5"
+    YA_INSTALLER_CORE="pre-rel-v0.11.0-rc11"
      return
 ;;
     esac
@@ -40,7 +43,7 @@ select_version() {
 select_version || exit 1
 
 YA_INSTALLER_WASI=${YA_INSTALLER_WASI:-v0.2.2}
-YA_INSTALLER_VM=${YA_INSTALLER_VM:-v0.2.11}
+YA_INSTALLER_VM=${YA_INSTALLER_VM:-v0.2.13}
 
 version_name() {
 	local name
@@ -87,7 +90,7 @@ downloader() {
     elif [ "$_dld" = curl ]; then
         curl --proto '=https' --silent --show-error --fail --location "$1" --output "$2"
     elif [ "$_dld" = wget ]; then
-        wget --https-only "$1" -O "$2"
+        wget -O "$2" --https-only "$1"
     else
         err "Unknown downloader"   # should not reach here
     fi
@@ -129,8 +132,10 @@ ensurepath() {
 
     say "" >&2
     say "Add $_required to your path" >&2
+    # shellcheck disable=SC2068,SC2016
     say 'HINT:   echo '\''export PATH="$HOME/.local/bin:$PATH"'\'" >> ~/${_rcfile}" >&2
     say "Update your current terminal." >&2
+    # shellcheck disable=SC2068,SC2016
     say 'HINT:   export PATH="$HOME/.local/bin:$PATH"' >&2
     exit 1
 }
@@ -149,18 +154,30 @@ EOF
     check_terms_accepted "$YA_INSTALLER_DATA/terms" "testnet-01.tag"
 }
 
+create_tags() {
+  local _dir="$1"
+  mkdir -p "$_dir"
+  shift
+  local _tag
+  for _tag in "$@"; do
+    touch "${_dir}/${_tag}"
+  done
+}
+
 check_terms_accepted() {
     local _tagdir="$1"
-    local _tags=${@:2}
+    shift
 
-    files_exist "$_tagdir" $_tags && return
-    while ! files_exist "$_tagdir" $_tags; do
-        read -r -u 2 -p "Do you accept the terms and conditions? [yes/no]: " ANS || exit 1
+    [ "$GOLEM_ACCEPT_TOS" = "yes" ] && create_tags "$_tagdir" "$@"
+
+    files_exist "$_tagdir" "$@" && return
+    local _read_opts="-r -u 2"
+    [ "${BASH_VERSION:-no}" = "no" ] && _read_opts=-r
+    while ! files_exist "$_tagdir" "$@"; do
+        # shellcheck disable=SC2162,SC2229
+        read ${_read_opts} -p "Do you accept the terms and conditions? [yes/no]: " ANS || exit 1
         if [ "$ANS" = "yes" ]; then
-            mkdir -p "$_tagdir"
-            for _tag in $_tags; do
-                touch "$_tagdir/$_tag"
-            done
+            create_tags "$_tagdir" "$@"
         elif [ "$ANS" = "no" ]; then
             exit 1
         else
@@ -170,8 +187,10 @@ check_terms_accepted() {
 }
 
 files_exist() {
-    for _file in ${@:2}; do
-        test ! -f "$1/$_file" && return 1
+    local dir=$1
+    shift
+    for _file in "$@"; do
+        test ! -f "$dir/$_file" && return 1
     done
     return 0
 }
@@ -270,6 +289,16 @@ download_vm() {
     echo -n "$YA_INSTALLER_DATA/bundles/ya-runtime-vm-${_ostype}-${YA_INSTALLER_VM}"
 }
 
+download_resources() {
+    local _resources_dir _url
+    _resources_dir="$(mktemp -d /tmp/ya_installer_resources.XXXX)"
+    _url="https://github.com/golemfactory/ya-installer-resources/releases/latest/download/resources.tar.gz"
+    _dl_start "Downloading certificates and whitelists" ""
+    (downloader "$_url" - | tar -C "$_resources_dir" -xz -f -) || err "failed to download $_url"
+    [[ -d "$_resources_dir/certs" ]] || mkdir "$_resources_dir/certs"
+    _dl_end
+    echo -n "$_resources_dir"
+}
 
 install_bins() {
     local _bin _dest _ln
@@ -302,6 +331,26 @@ install_plugins() {
   mkdir -p "$_dst"
 
   (cd "$_src" && cp -r ./* "$_dst")
+}
+
+setup_provider() {
+  local _bin_dir _resources_dir
+  _bin_dir="$1"
+  _resources_dir=$(download_resources) || exit 1
+
+  if [[ "${YA_INSTALLER_CORE}" =~ .*v0.12.0-rc1.* ]] || [[ "${YA_INSTALLER_CORE}" =~ .*v0.12.0-rc2.* ]] || [[ "${YA_INSTALLER_CORE}" =~ .*v0.11.* ]] || [[ "${YA_INSTALLER_CORE}" =~ .*v0.10.* ]] || [[ "${YA_INSTALLER_CORE}" =~ .*v0.9.* ]] || [[ "${YA_INSTALLER_CORE}" =~ .*v0.8.* ]] || [[ "${YA_INSTALLER_CORE}" =~ .*v0.7.* ]] || [[ "${YA_INSTALLER_CORE}" =~ .*v0.6.* ]] || [[ "${YA_INSTALLER_CORE}" =~ .*v0.5.* ]] || [[ "${YA_INSTALLER_CORE}" =~ .*v0.4.* ]] || [[ "${YA_INSTALLER_CORE}" =~ .*v0.3.* ]]; then
+    :
+  elif [[ "${YA_INSTALLER_CORE}" =~ .*v0.12.* ]]; then
+    $_bin_dir/ya-provider keystore add $(find $_resources_dir/certs -type f) --permissions outbound-manifest|unverified-permissions-chain >/dev/null 2>&1
+    $_bin_dir/ya-provider whitelist add -t regex -p $(cat $_resources_dir/whitelist/regex.lst | tr '\n' ' ') >/dev/null 2>&1
+    $_bin_dir/ya-provider whitelist add -t strict -p $(cat $_resources_dir/whitelist/strict.lst | tr '\n' ' ') >/dev/null 2>&1
+  else
+    $_bin_dir/ya-provider keystore add $(find $_resources_dir/certs -type f) --permissions outbound-manifest|unverified-permissions-chain >/dev/null 2>&1
+    $_bin_dir/ya-provider whitelist add -t regex -p $(cat $_resources_dir/whitelist/regex.lst | tr '\n' ' ') >/dev/null 2>&1
+    $_bin_dir/ya-provider whitelist add -t strict -p $(cat $_resources_dir/whitelist/strict.lst | tr '\n' ' ') >/dev/null 2>&1
+  fi
+
+  rm -rf "$_resources_dir"
 }
 
 main() {
@@ -341,7 +390,10 @@ main() {
       test -n "$_src_vm" && install_plugins "$_src_vm" "$YA_INSTALLER_LIB"
       (
         PATH="$YA_INSTALLER_BIN:$PATH"
-        RUST_LOG=error "$_src_core/golemsp" setup <&2
+        if test "${BATCH_MODE}" = "no"; then
+          RUST_LOG=error "$_src_core/golemsp" setup <&2 || exit 1
+        fi
+        setup_provider "$_src_core"
       )
     fi
 
