deploy: b9492346785cdcd292f042d2925716f3793bcc98

diff --git a/dev/as-requestor b/dev/as-requestor
--- a/dev/as-requestor
+++ b/dev/as-requestor
@@ -1,7 +1,7 @@
 #! /bin/bash
 # shellcheck shell=bash
 
-set -u
+set -eu
 
 GOLEM_ACCEPT_TOS="${GOLEM_ACCEPT_TOS:-no}"
 BATCH_MODE="${BATCH_MODE:-no}"
@@ -9,32 +9,32 @@ BATCH_MODE="${BATCH_MODE:-no}"
 YA_INSTALLER_VARIANT=requestor
 select_version() {
   echo "available versions:"
-  echo "0) v0.13.1 #323"
-  echo "1) v0.13.0-rc21 #322"
-  echo "2) v0.13.0-rc20 #321"
-  echo "3) v0.13.0-rc19 #320"
-  echo "4) v0.13.0-rc18 #318"
+  echo "0) v0.13.1-rc0 #324"
+  echo "1) v0.13.1 #323"
+  echo "2) v0.13.0-rc21 #322"
+  echo "3) v0.13.0-rc20 #321"
+  echo "4) v0.13.0-rc19 #320"
   while true; do
     read -r -u 2 -p "Select version: " ANS || exit 1
     case "$ANS" in
     0)
-    YA_INSTALLER_CORE="pre-rel-v0.13.1"
+    YA_INSTALLER_CORE="pre-rel-v0.13.1-rc0"
      return
 ;;
     1)
-    YA_INSTALLER_CORE="pre-rel-v0.13.0-rc21"
+    YA_INSTALLER_CORE="pre-rel-v0.13.1"
      return
 ;;
     2)
-    YA_INSTALLER_CORE="pre-rel-v0.13.0-rc20"
+    YA_INSTALLER_CORE="pre-rel-v0.13.0-rc21"
      return
 ;;
     3)
-    YA_INSTALLER_CORE="pre-rel-v0.13.0-rc19"
+    YA_INSTALLER_CORE="pre-rel-v0.13.0-rc20"
      return
 ;;
     4)
-    YA_INSTALLER_CORE="pre-rel-v0.13.0-rc18"
+    YA_INSTALLER_CORE="pre-rel-v0.13.0-rc19"
      return
 ;;
     esac
@@ -46,10 +46,10 @@ YA_INSTALLER_WASI=${YA_INSTALLER_WASI:-v0.2.2}
 YA_INSTALLER_VM=${YA_INSTALLER_VM:-v0.3.0}
 
 version_name() {
-	local name
+    local name
 
-	name=${1#pre-rel-}
-	printf "%s" "${name#v}"
+    name=${1#pre-rel-}
+    printf "%s" "${name#v}"
 }
 
 say() {
@@ -57,7 +57,7 @@ say() {
 }
 
 err() {
-    say "$1" >&2
+    echo -e "\033[1;31m$1\033[0m" >&2
     exit 1
 }
 
@@ -68,7 +68,7 @@ need_cmd() {
 }
 
 check_cmd() {
-    command -v "$1" > /dev/null 2>&1
+    command -v "$1" >/dev/null 2>&1
 }
 
 assert_nz() {
@@ -92,7 +92,7 @@ downloader() {
     elif [ "$_dld" = wget ]; then
         wget -O "$2" --https-only "$1"
     else
-        err "Unknown downloader"   # should not reach here
+        err "Unknown downloader" # should not reach here
     fi
 }
 
@@ -114,8 +114,7 @@ ensurepath() {
     _required="$1"
     _save_ifs="$IFS"
     IFS=":"
-    for _path in $PATH
-    do
+    for _path in $PATH; do
         if [ "$_path" = "$_required" ]; then
             IFS="$_save_ifs"
             return
@@ -124,19 +123,20 @@ ensurepath() {
     IFS="$_save_ifs"
 
     case "${SHELL:-/bin/sh}" in
-      */bash) _rcfile=".bashrc" ;;
-      */zsh) _rcfile=".zshrc" ;;
-      *) _rcfile=".profile"
+    */bash) _rcfile=".bashrc" ;;
+    */zsh) _rcfile=".zshrc" ;;
+    *)
+        _rcfile=".profile"
         ;;
     esac
 
-    say "" >&2
-    say "Add $_required to your path" >&2
-    # shellcheck disable=SC2068,SC2016
-    say 'HINT:   echo '\''export PATH="$HOME/.local/bin:$PATH"'\'" >> ~/${_rcfile}" >&2
-    say "Update your current terminal." >&2
-    # shellcheck disable=SC2068,SC2016
-    say 'HINT:   export PATH="$HOME/.local/bin:$PATH"' >&2
+    echo -e "\e[1;31m\n[ATTENTION REQUIRED]\e[0m"
+    echo -e "\e[1;34mTo ensure your system can find the Golem binaries, please include '$_required' within your path, by following the instructions below.\e[0m"
+    echo -e "\e[1;33m1. Add the path to your configuration file:\e[0m"
+    echo -e "\e[0;32m   echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/${_rcfile}\e[0m"
+    echo -e "\e[1;33m2. Apply the changes in your current terminal:\e[0m"
+    echo -e "\e[0;32m   export PATH=\"\$HOME/.local/bin:\$PATH\"\e[0m"
+
     exit 1
 }
 
@@ -155,13 +155,13 @@ EOF
 }
 
 create_tags() {
-  local _dir="$1"
-  mkdir -p "$_dir"
-  shift
-  local _tag
-  for _tag in "$@"; do
-    touch "${_dir}/${_tag}"
-  done
+    local _dir="$1"
+    mkdir -p "$_dir"
+    shift
+    local _tag
+    for _tag in "$@"; do
+        touch "${_dir}/${_tag}"
+    done
 }
 
 check_terms_accepted() {
@@ -209,35 +209,41 @@ detect_dist() {
             fi
         fi
 
-        # On macOS M1 we want to run x86 binaries using Rosetta,
-        # because we don't have compatible ARM builds.
         case "$_cputype" in arm64 | aarch64)
+            if [ "$YA_INSTALLER_VARIANT" = "provider" ]; then
+                err "We do not support running a provider on ARM devices yet. Please use an x86_64 machine to install the provider."
+            fi
+            # On macOS M1 we want to run x86 binaries using Rosetta,
+            # because we don't have compatible ARM builds.
             _cputype=x86_64
             ;;
         esac
+
     fi
 
-
     case "$_cputype" in
-        x86_64 | x86-64 | x64 | amd64)
-            _cputype=x86_64
-            ;;
-        *)
-            err "invalid cputype: $_cputype"
-            ;;
+    x86_64 | x86-64 | x64 | amd64)
+        _cputype=x86_64
+        ;;
+    *)
+        if [ "$YA_INSTALLER_VARIANT" = "provider" ]; then
+            err "We do not support running a provider on ARM devices yet. Please use an x86_64 machine to install the provider."
+        fi
+        ;;
     esac
     case "$_ostype" in
-        Linux)
-            _ostype=linux
-            ;;
-        Darwin)
-            _ostype=osx
-            ;;
-        MINGW* | MSYS* | CYGWIN*)
-            _ostype=windows
-            ;;
-        *)
-            err "invalid os type: $_ostype"
+    Linux)
+        _ostype=linux
+        ;;
+    Darwin)
+        _ostype=osx
+        ;;
+    MINGW* | MSYS* | CYGWIN*)
+        _ostype=windows
+        ;;
+    *)
+        err "invalid os type: $_ostype"
+        ;;
     esac
     echo -n "$_ostype"
 }
@@ -251,7 +257,7 @@ _dl_head() {
 }
 
 _dl_start() {
-	printf "%-20s %25s " "$1" "$(version_name "$2")" >&2
+    printf "%-20s %25s " "$1" "$(version_name "$2")" >&2
 }
 
 _dl_end() {
@@ -267,7 +273,7 @@ download_core() {
 
     _url="https://github.com/golemfactory/yagna/releases/download/${YA_INSTALLER_CORE}/golem-${_variant}-${_ostype}-${YA_INSTALLER_CORE}.tar.gz"
     _dl_start "golem core" "$YA_INSTALLER_CORE"
-    (downloader "$_url" - | tar -C "$YA_INSTALLER_DATA/bundles" -xz -f - ) || return 1
+    (downloader "$_url" - | tar -C "$YA_INSTALLER_DATA/bundles" -xz -f -) || return 1
     _dl_end
     echo -n "$YA_INSTALLER_DATA/bundles/golem-${_variant}-${_ostype}-${YA_INSTALLER_CORE}"
 }
@@ -315,38 +321,37 @@ install_bins() {
 
     _dest="$2"
     if [ "$_dest" = "/usr/bin" ] || [ "$_dest" = "/usr/local/bin" ]; then
-      _ln="cp"
-      test -w "$_dest" || {
-        _ln="sudo cp"
-        say "to install to $_dest, root privileges required"
-      }
+        _ln="cp"
+        test -w "$_dest" || {
+            _ln="sudo cp"
+            say "to install to $_dest, root privileges required"
+        }
     else
-      _ln="ln -sf"
+        _ln="ln -sf"
     fi
 
-    for _bin in "$1"/*
-    do
+    for _bin in "$1"/*; do
         if [ -f "$_bin" ] && [ -x "$_bin" ]; then
-           #echo -- $_ln -- "$_bin" "$_dest"
-           $_ln -- "$_bin" "$_dest"
+            #echo -- $_ln -- "$_bin" "$_dest"
+            $_ln -- "$_bin" "$_dest"
         fi
     done
 }
 
 install_plugins() {
-  local _src _dst
+    local _src _dst
 
-  _src="$1"
-  _dst="$2/plugins"
-  mkdir -p "$_dst"
+    _src="$1"
+    _dst="$2/plugins"
+    mkdir -p "$_dst"
 
-  (cd "$_src" && cp -r ./* "$_dst")
+    (cd "$_src" && cp -r ./* "$_dst")
 }
 
 setup_provider() {
-  local _bin_dir _resources_dir
-  _bin_dir="$1"
-  _resources_dir=$(download_resources) || exit 1
+local _bin_dir _resources_dir
+_bin_dir="$1"
+_resources_dir=$(download_resources) || exit 1
 
   if [[ "${YA_INSTALLER_CORE}" =~ .*v0.12.0-rc1.* ]] || [[ "${YA_INSTALLER_CORE}" =~ .*v0.12.0-rc2.* ]] || [[ "${YA_INSTALLER_CORE}" =~ .*v0.11.* ]] || [[ "${YA_INSTALLER_CORE}" =~ .*v0.10.* ]] || [[ "${YA_INSTALLER_CORE}" =~ .*v0.9.* ]] || [[ "${YA_INSTALLER_CORE}" =~ .*v0.8.* ]] || [[ "${YA_INSTALLER_CORE}" =~ .*v0.7.* ]] || [[ "${YA_INSTALLER_CORE}" =~ .*v0.6.* ]] || [[ "${YA_INSTALLER_CORE}" =~ .*v0.5.* ]] || [[ "${YA_INSTALLER_CORE}" =~ .*v0.4.* ]] || [[ "${YA_INSTALLER_CORE}" =~ .*v0.3.* ]]; then
     :
@@ -364,12 +369,13 @@ setup_provider() {
     $_bin_dir/golemsp manifest-bundle add $_resources_dir >/dev/null 2>&1
   fi
 
-  rm -rf "$_resources_dir"
+rm -rf "$_resources_dir"
 }
 
 main() {
     local _ostype _src_core _bin _src_wasi _src_vm
 
+    _ostype="$(detect_dist)" || exit 1
     downloader --check
     need_cmd uname
     need_cmd chmod
@@ -383,32 +389,30 @@ main() {
 
     test -d "$YA_INSTALLER_BIN" || mkdir -p "$YA_INSTALLER_BIN"
 
-    _ostype="$(detect_dist)"
-
     _dl_head
     _src_core=$(download_core "$_ostype" "$YA_INSTALLER_VARIANT") || return 1
     if [ "$YA_INSTALLER_VARIANT" = "provider" ]; then
-      _src_wasi=$(download_wasi "$_ostype")
-      if [ "$_ostype" = "linux" ]; then
-        _src_vm=$(download_vm "$_ostype") || exit 1
+        _src_wasi=$(download_wasi "$_ostype")
+        if [ "$_ostype" = "linux" ]; then
+            _src_vm=$(download_vm "$_ostype") || exit 1
 
-      fi
+        fi
     fi
 
     install_bins "$_src_core" "$YA_INSTALLER_BIN"
     if [ "$YA_INSTALLER_VARIANT" = "provider" ]; then
-      install_plugins "$_src_core/plugins" "$YA_INSTALLER_LIB"
-      # Cleanup core plugins to make ya-provider use ~/.local/lib/yagna/plugins
-      rm -rf "$_src_core/plugins"
-      install_plugins "$_src_wasi" "$YA_INSTALLER_LIB"
-      test -n "$_src_vm" && install_plugins "$_src_vm" "$YA_INSTALLER_LIB"
-      (
-        PATH="$YA_INSTALLER_BIN:$PATH"
-        if test "${BATCH_MODE}" = "no"; then
-          RUST_LOG=error "$_src_core/golemsp" setup <&2 || exit 1
-        fi
-        setup_provider "$_src_core"
-      )
+        install_plugins "$_src_core/plugins" "$YA_INSTALLER_LIB"
+        # Cleanup core plugins to make ya-provider use ~/.local/lib/yagna/plugins
+        rm -rf "$_src_core/plugins"
+        install_plugins "$_src_wasi" "$YA_INSTALLER_LIB"
+        test -n "$_src_vm" && install_plugins "$_src_vm" "$YA_INSTALLER_LIB"
+        (
+            PATH="$YA_INSTALLER_BIN:$PATH"
+            if test "${BATCH_MODE}" = "no"; then
+                RUST_LOG=error "$_src_core/golemsp" setup <&2 || exit 1
+            fi
+            setup_provider "$_src_core"
+        )
     fi
 
     ensurepath "$YA_INSTALLER_BIN"
